#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("rmpdv.Resource", IsApplication=true)]

namespace rmpdv
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::rmpdv.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BarraProgressoStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BtnLoginStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BtnSairStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialogoacima = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialogodireita = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DialogoLogin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EditEntrar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int login = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logout = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monoandroidsplash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pesquisa = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int PesquisaStyle = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int ListaProduto = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int btnEntar = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int btnLogin = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int btnSair = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int edtCodigo = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int edtPreco = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int edtProduto = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int edtSenha = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int edtUsuario = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int edtpesquisa = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int layoutPrincipal = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int llContainer = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int pesquisa = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int progressoBar = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout1 = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int txtSenha = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int txtSeparador1 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int txtSeparador2 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int txtTitulo = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int txtUsuario = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int txxCabecalhoProduto = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DialogoLogin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int produtos = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProdutosListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int BarraAcao = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AnimacaoDialogo = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
