#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("rmpdv.Resource", IsApplication=true)]

namespace rmpdv
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::rmpdv.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int ListaProduto = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int btnLogin = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int btnPesquisa = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int btnSair = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int btnVoltar = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int edtCodigo = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int edtPreco = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int edtProduto = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int edtSenha = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int edtUsuario = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int edtpesquisa = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int layotProduto = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout2 = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout3 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout4 = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int space1 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int titulo = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int txtLogin = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int txtPesquisa = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int txtSenha = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int produtos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProdutosListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
