#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("rmpdv.Resource", IsApplication=true)]

namespace rmpdv
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::rmpdv.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BarraMenuPrincipalStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BarraProgressoStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BtnLoginStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BtnSairStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int comanda = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int comandas = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int consuminterno = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int consumointerno = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dialogoacima = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dialogodireita = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DialogoLogin = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int EditEntrar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int login = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pesquisa = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int PesquisaStyle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rm = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int saida = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int senha = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int senhas = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int voltar = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070020
			public const int ListaProduto = 2131165216;
			
			// aapt resource value: 0x7f070016
			public const int btnEntar = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int btnLogin = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int btnSair = 2131165212;
			
			// aapt resource value: 0x7f070023
			public const int edtCodigo = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int edtPreco = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int edtProduto = 2131165220;
			
			// aapt resource value: 0x7f070015
			public const int edtSenha = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int edtUsuario = 2131165203;
			
			// aapt resource value: 0x7f070021
			public const int edtpesquisa = 2131165217;
			
			// aapt resource value: 0x7f070007
			public const int imageView1 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int imageView2 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int imageView3 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int imageView4 = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int lComanda = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int lConsumoInterno = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int lSaida = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int lSenha = 2131165196;
			
			// aapt resource value: 0x7f070017
			public const int layoutPrincipal = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout3 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout4 = 2131165187;
			
			// aapt resource value: 0x7f07001e
			public const int llContainer = 2131165214;
			
			// aapt resource value: 0x7f070026
			public const int pesquisa = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int progressBar = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int relativeLayout1 = 2131165213;
			
			// aapt resource value: 0x7f070008
			public const int textView1 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int textView4 = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int textView5 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView6 = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int txtSenha = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int txtSeparador1 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int txtSeparador2 = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int txtTitulo = 2131165208;
			
			// aapt resource value: 0x7f070012
			public const int txtUsuario = 2131165202;
			
			// aapt resource value: 0x7f07001f
			public const int txxCabecalhoProduto = 2131165215;
			
			// aapt resource value: 0x7f070027
			public const int voltarproduto = 2131165223;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarraMenuPrincipal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogoLogin = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuPrincipal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int produtos = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ProdutosListItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int BarraAcao = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ActionBarMenuPrincipal = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int AnimacaoDialogo = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MenuPrincipalTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
